config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get 'heros', to: 'heros#index'
  # post 'heros', to: 'heros#create'
  # get 'heros/new', to: 'heros#new', as: 'new_hero'
  # get 'heros/:id/edit', to: 'heros#edit', as: 'edit_hero'
  # get 'heros/:id', to: 'heros#show'
  # patch 'heros/:id', to: 'heros#update'
  # put 'heros/:id', to: 'heros#update'
  # delete 'heros/:id', to: 'heros#destroy', as: 'delete_hero'
  resources :heros do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index, :destroy, :show, :update, :edit] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :hero
  belongs_to :user
  has_one :review

  validates :date, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :description, presence: true
end

app/models/hero.rb
class Hero < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many_attached :photos
  # has_many :reviews, through: :bookings

  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :price, numericality: { only_integer: true }

  include PgSearch::Model
  pg_search_scope :search_by_name_skill_description,
    against: {
      name: 'A',
      skill: 'B',
      description: 'C'
    },
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking

  validates :rating, presence: true
  validates :rating, numericality: { only_integer: true, less_than_or_equal_to: 5, greater_than: 0 }
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :heroes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show edit update destroy]
  def index
    @bookings = policy_scope(Booking)
  end

  def show
    authorize @booking
  end

  def new
    @booking = Booking.new
    @hero = Hero.find(params[:hero_id])
    authorize @booking
  end

  def edit
    authorize @booking
  end

  def create
    @hero = Hero.find(params[:hero_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.hero = @hero
    authorize @booking
    if @booking.save
      redirect_to booking_path(@booking)
      # redirect_to hero_path(@booking.hero)
    else
      render :new
    end
  end

  def update
    authorize @booking
    if @booking.update!(booking_params)
      redirect_to booking_path(@booking), notice: 'Booking was successfully updated'
    else
      render :edit
    end
  end

  def destroy
    authorize @booking
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:date, :start_time, :end_time, :description)
  end

  def set_booking
    @booking = Booking.where(user: current_user).find(params[:id])
  end
end

app/controllers/heros_controller.rb
class HerosController < ApplicationController
  before_action :set_hero, only: [:show, :edit, :update, :destroy]
  def index
    if params[:query].present?
      @heros = policy_scope(Hero.search_by_name_skill_description(params[:query]))
    else
      @heros = policy_scope(Hero)
    end
  end

  def show
    authorize @hero
    @booking = Booking.new
  end

  def new
    @hero = Hero.new
    authorize @hero
  end

  def edit
    authorize @hero
  end

  def create
    # @user = User.find(params[:user_id])
    @hero = Hero.new(hero_params)
    @hero.user = current_user
    authorize @hero
    if @hero.save
      redirect_to hero_path(@hero)
    else
      render :new
    end
  end

    # PATCH/PUT /heros/1
  def update
    if @hero.update(hero_params)
      authorize @hero
      redirect_to hero_path(@hero), notice: 'Hero was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize @hero
    @hero.destroy
    redirect_to heros_path
  end

  private

  def hero_params
    params.require(:hero).permit(:name, :description, :price, :skill, photos: [])
  end

  def set_hero
    @hero = Hero.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :show, :index]

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[show edit update destroy]

  def index
    @reviews = policy_scope(Review)
  end

  def show
    authorize @review
  end

  def new
    @review = Review.new
    @booking = Booking.find(params[:booking_id])
    authorize @review
  end

  def edit
    authorize @review
  end

  def create
    @booking = Booking.find(params[:booking_id])
    @review = Review.new(review_params)
    # @review.booking.user = current_user
    @review.booking = @booking
    authorize @review
    if @review.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  def update
    if @review.update(review_params)
      authorize @review
      redirect_to booking_path(@booking), notice: 'Booking was successfully updated'
    else
      render :edit
    end
  end

  def destroy
    authorize @review
    @review.destroy
    redirect_to bookings_path
  end

  private

  def review_params
    params.require(:review).permit(:rating, :description)
  end

  def set_review
    @review = Review.where(user: current_user).find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_active?(link_path)
    current_page?(link_path) ? "active" : ""
  end
end

app/views/bookings/edit.html.erb
<div class="container">
  <%= simple_form_for @booking do |f| %>
    <%= f.input :date %>
    <%= f.input :start_time %>
    <%= f.input :end_time %>
    <%= f.input :description %>
    <%= f.submit %>
  <% end %>
</div>

<div>
  <%= link_to  "Back to booking", booking_path(@booking) %>
</div>

app/views/bookings/index.html.erb
<div class="container">
  <h1>All you your Bookings</h1>
    <% @bookings.each do |booking| %>
      <div class="comicform">
        <div class="evenboxinner">
          <%= link_to edit_booking_path(booking) do %><i class='far fa-edit'></i>
             <% end %>
          <% if policy(booking).destroy? %>
            <%= link_to booking_path(booking),
              method: :delete,
              data: { confirm: "Are you sure?" } do %><i class="far fa-trash-alt"></i>
            <% end %>
           <% end %>
        </div>
        <h2>Booking #<%= link_to  booking.id, booking_path(booking) %> for: </h2>
        <p>Hero: <%= link_to  booking.hero.name, booking_path(booking) %></p>
        <p>Date: <%= booking.date %></p>
        <% if booking.date < Date.today %>
          <p><%= (Date.today - booking.date).to_i.abs %> day(s) ago</p>
        <% else %>
          <p>In <%= (booking.date - Date.today).to_i.abs %> day(s)</p>
        <% end %>
      </div>
  <% end %>
</div>

app/views/bookings/new.html.erb
<div class="d-flex justify-content-center">
  <div class="d-inline-flex flex-column comicheader">
    <h1>Book <%= @hero.name %></h1>
  </div>
</div>

<br>
<div class="d-flex justify-content-center">
  <div class="container">
    <div class="comicform">
      <%= simple_form_for [@hero, @booking] do |f| %>
        <%= f.input :date %>
        <%= f.input :start_time, as: :time %>
        <%= f.input :end_time, as: :time %>
        <%= f.input :description, as: :text %>
        <%= f.button :submit, class: "comicbtn" %>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="d-flex justify-content-center">
  <div class="container justify-content-center">
    <div class="comicform">
      <div class="evenboxinner">
        <%= link_to edit_booking_path(@booking) do %><i class='far fa-edit'></i>
           <% end %>
        <% if policy(@booking).destroy? %>
          <%= link_to booking_path,
            method: :delete,
            data: { confirm: "Are you sure?" } do %><i class="far fa-trash-alt"></i>
          <% end %>
         <% end %>
      </div>
      <h1>Booking for: <%= link_to  @booking.hero.name, hero_path(@booking.hero) %></h1>
      <br>
      <% if @booking.date < Date.today %>
          <h3><%= (Date.today - @booking.date).to_i.abs %> day(s) ago</h3>
      <% else %>
          <p>In <%= (@booking.date - Date.today).to_i.abs %> day(s)</p>
      <% end %>
      <p>Date:</p> <h3><%= @booking.date %></h3>
      <p>Start time:</p> <h3><%= @booking.start_time.strftime("%I:%M%p") %></h3>
      <p>End time:</p> <h3><%= @booking.end_time.strftime("%I:%M%p") %></h3>
      <p>Your emergency: <%= @booking.description %></p>
      <div class="row">
        <%= link_to "Leave a Review", new_booking_review_path(@booking), class: 'comicbtn2' %>
        <%= link_to @booking.hero.name, hero_path(@booking.hero), class: 'comicbtn2' %>
        <%= link_to "Back to all Heroes", heros_path, class: 'comicbtnback' %>
      </div>
    </div>
  </div>
</div>

app/views/heros/edit.html.erb
<div class="container">
  <%= simple_form_for @hero do |f| %>
    <%= f.input :name %>
    <%= f.input :skill %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%#= f.number_field (:price, in: ${1.0..200.0}, step: ${0.5}) %>
    <%= f.submit %>
  <% end %>
</div>

<div>
  <%= link_to  "Back to hero", hero_path(@hero) %>
</div>

app/views/heros/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://miro.medium.com/max/1400/0*zL5gOejQqzvWdaF1.jpg);">
  <div class="d-flex justify-content-center">
    <div class="d-inline-flex flex-column">
      <h1>Find your hero</h1>
      <br>
      <%= render "shared/search" %>
      <br>
    </div>
  </div>
</div>


<div class="container">
  <br>
  <div class="row">
    <% @heros.each do |hero| %>
      <div class="col-lg-4">
        <% if hero.photos.attached? %>
          <div class="box box2" style="background-image: url('<%= cl_image_path hero.photos.first.key, :width=>358, :height=>262, :crop=>'fill' %>')">
        <% else %>
            <div class="box box2" style="background-image: url('https://blog.dana-farber.org/insight/wp-content/uploads/2014/09/452186425-Converted.jpg.jpg')">
        <% end %>
          <div class="evenboxinner"><%= hero.name %></div>
          <div class="evenboxinnerdown"><%= hero.price %>€</div>
          <div class="oddboxinner">
          <% counter = 1 %>
          <% sum = 5 %>
          <% hero.bookings.each do |booking| %>
          <% if booking.review.present? %>
            <% sum += booking.review.rating %>
            <% counter += 1 %>
          <% end %>
          <% end %>
          <% (sum / counter.to_i).times do %>
              <i class="fas fa-star"></i>
              <% end %>
        <%= link_to "", hero_path(hero), class: 'card-link' %>
        </div>
        <%= link_to "", hero_path(hero), class: 'card-link' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/heros/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(https://www.ppt-backgrounds.net/uploads/comic-book-wallpaper-background.jpg);">
  <div class="d-flex justify-content-center">
    <div class="d-inline-flex flex-column">
      <h1>Be a hero</h1>
    </div>
  </div>
</div>
<br>
<div class="d-flex justify-content-center">
  <div class="container">
    <div class="comicformoverlap">
      <%= simple_form_for @hero do |f| %>
        <%= f.input :name %>
        <%= f.input :skill %>
        <%= f.input :description %>
        <%= f.input :price %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%#= f.number_field (:price, in: ${1.0..200.0}, step: ${0.5}) %>
        <%= f.button :submit, class: "comicbtn" %>
      <% end %>
    </div>
  </div>
</div>

app/views/heros/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.1)), url(https://wallpapercave.com/wp/wp3433423.gif);">
  <div class="d-flex justify-content-center">
    <div class="d-inline-flex flex-column">
      <h1><%= @hero.name %></h1>
    </div>
  </div>
</div>



  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-6">
        <% if @hero.photos.attached? %>
        <div class="box box3" style="background-image: url('<%= cl_image_path @hero.photos.first.key, :width=>358, :height=>262, :crop=>'fill' %>')">
          <% else %>
          <div class="box box3" style="background-image: url('https://blog.dana-farber.org/insight/wp-content/uploads/2014/09/452186425-Converted.jpg.jpg')">
            <% end %>
            <div class="evenboxreviewleft">
              <h3><% if policy(@hero).edit? %>
                <%= link_to edit_hero_path(@hero) do %><i class='far fa-edit'></i>
                  <% end %>
                <% end %>
                <% if policy(@hero).destroy? %>
                  <%= link_to hero_path,
                  method: :delete,
                  data: { confirm: "Are you sure?" } do %><i class="far fa-trash-alt"></i>
                  <% end %>
                <% end %>
              </h3>
            </div>
          </div>
        </div>

        <div class="col-sm-12 col-md-2">
          <div class="box box1"><h3><%= @hero.price %> €/Hr</h3></div>
          <div class="box box5"><h3>Powers: <%= @hero.skill %></h3></div>
          <div class="box box4"><h5><%= @hero.description %></h5></div>
        </div>
        <div class="col-sm-12 col-md-1">
          <% counter = 1 %>
          <% sum = 5 %>
          <% @hero.bookings.each do |booking| %>
          <% if booking.review.present? %>
            <% sum += booking.review.rating %>
            <% counter += 1 %>
          <% end %>
          <% end %>
          <div class="box box1"><h5><% (sum / counter.to_i).times do %>
              <i class="fas fa-star"></i>
            <% end %>
          </h5></div>
        </div>
      </div>

    <div class="row">
      <%= link_to  "Book me!", new_hero_booking_path(@hero), class: 'comicbtn2' %>
       <%= link_to  "Back to all Heroes", heros_path, class: 'comicbtnback' %>
    </div>
    <br>
    <br>
    <div class="row">
      <div class="evenboxreview"><h3>Reviews</h3></div>
    </div>
    <% @hero.bookings.each do |booking| %>
    <% if booking.review.present? %>
    <div class="row mt-3">
      <div class="box box6">
        <p><%= booking.review.description %></p>
        <div class="evenboxstar">
          <h4><% booking.review.rating.times do %>
           <i class="fas fa-star"></i>
           <% end %>
          <% end %></h4>
        </div>
      </div>
    </div>
    <% end %>

    <div class="evenboxinnernew">
      <div class="booking">
        <% @hero.bookings.each do |booking|  %>
        <p>Booked for: <%= booking.date %></p>
        <% end %>
      </div>
    </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeMyHero</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <!-- <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->
    <%= render 'shared/flashes' %>
      <div id="page-container">
        <div id="content-wrap">
          <div class="navbar-container">
            <%= render "shared/navbar" %>
          </div>
          <div class="content-container">
           <%= yield %>
          </div>
          <div class="footer-container">
           <%= render "shared/footer" %>
          </div>
      </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner h-100 w-100 d-inline-block" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/a4637adf-84a6-4eba-8020-71e9a0452e82/dddb6n7-74f074c6-bd9b-4814-9bdb-9fe369d842df.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOiIsImlzcyI6InVybjphcHA6Iiwib2JqIjpbW3sicGF0aCI6IlwvZlwvYTQ2MzdhZGYtODRhNi00ZWJhLTgwMjAtNzFlOWEwNDUyZTgyXC9kZGRiNm43LTc0ZjA3NGM2LWJkOWItNDgxNC05YmRiLTlmZTM2OWQ4NDJkZi5wbmcifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6ZmlsZS5kb3dubG9hZCJdfQ.3xUgsT6-OKzpF0MLg8njPShJZLdsHrD_EP0ylLvfk4g);">
  <div class="d-flex justify-content-center">
    <div class="d-inline-flex flex-column">
      <div class="container">
        <h1>Be My Hero</h1>
        <p>not the hero you deserve,<br> but the one you can afford</p>
        <a class="button comicbtn" href="/heros">Save Me</a>
      </div>
    </div>
  </div>
</div>



<div class="container home">
  <div class="bubble left">Have a city or small planet that needs saving, or just looking for someone to get your cat out of a tree and help with groceries? Find any hero for the job. </div>
  <div class="bubble right">We offer some of the finest hero and heroines the multiverse has to offer, all just one click away... </div>
  <div class="bubble think left">
    <%= simple_form_for :search, url: root_path, method: :get do |f| %>
        <div class="search-form-control form-group">
          <input class="form-control string required" type="text" name="search[query]" id="search_query" />
          <button name="button" type="submit" class="btn btn-flat">
            <i class="fas fa-search"></i> Search
          </button>
        </div>
      <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="d-flex justify-content-center">
  <div class="d-inline-flex flex-column comicheader text-center">
    <h1>Review <%= @booking.hero.name %></h1>
    <h2>Let us know how you liked <%= @booking.hero.name %>'s service</h2>
  </div>
</div>

<br>
<div class="d-flex justify-content-center">
  <div class="container">
    <div class="comicform">
      <%= simple_form_for [@booking, @review] do |f| %>
        <%= f.input :rating %>
        <%= f.input :description %>
        <%= f.button :submit, class: "comicbtn" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
_flashes.html.erb

app/views/shared/_footer.html.erb
          <div class="footer-links">
            <a href="#"><i class="fab fa-github"></i></a>
            <a href="#"><i class="fab fa-instagram"></i></a>
            <a href="#"><i class="fab fa-facebook"></i></a>
            <a href="#"><i class="fab fa-twitter"></i></a>
            <a href="#"><i class="fab fa-linkedin"></i></a>
          </div>

app/views/shared/_navbar.html.erb
<header class="navbar navbar-expand-sm navbar-light navbar-lewagon" id="header">
	<%= link_to root_path, class: "navbar-brand" do %>
	<i class="fas fa-mask"></i>
	<% end %>

	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">

			<li class="nav-item <%= is_active?(heros_path) %>">
				<%= link_to "Get a Hero", heros_path, class: "nav-link" %>
			</li>

			<li class="nav-item <%= is_active?(new_hero_path) %>">
				<%= link_to "Be a Hero", new_hero_path, class: "nav-link" %>
			</li>
			<% if user_signed_in?  %>
				<li class="nav-item dropdown">
					<%= image_tag "https://cdn.iconscout.com/icon/free/png-512/avatar-370-456322.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
					<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
						<%= link_to "Bookings", bookings_path, class: "dropdown-item" %>
						<%= link_to "Your Profile", "#", class: "dropdown-item" %>
						<%= link_to "Sign Out", "#", class: "dropdown-item" %>
					</div>
				</li>
			<% end %>
		</ul>
</header>

app/views/shared/_search.html.erb
<div class="input-group justify-content-center">
  <div class="button comicsearch">
    <%= form_tag heros_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Search for a hero" %>
  </div>
      <%= submit_tag "Search", class: "comicsearch" %>
    <% end %>
  </div>